services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TMS_Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    image: ghcr.io/yang000301/testmanagementsystem-api:latest
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestManagementSystem;User Id=sa;Password=TMS_Password123!;TrustServerCertificate=True;
      - Jwt__Key=TMS_SuperSecretKey_2026_MustBe32CharactersLong!
      - Jwt__Issuer=TestManagementSystem
      - Jwt__Audience=TestManagementSystem
    depends_on:
      - db

  frontend:
    image: ghcr.io/yang000301/testmanagementsystem-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  sqldata: